package olympic.main.person;

import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * 为运动员随机生成姓名
 */
public class NameFactory {

        static String[] namesEn = {
                "Aaron",
                "Abel",
                "Abraham",
                "Adam",
                "Adrian",
                "Aidan",
                "Alva",
                "Alex",
                "Alexander",
                "Alan",
                "Albert",
                "Alfred",
                "Andrew",
                "Andy",
                "Angus",
                "Anthony",
                "Apollo",
                "Arnold",
                "Arthur",
                "August",
                "Austin",
                "Ben",
                "Benjamin",
                "Bert",
                "Benson",
                "Bill",
                "Billy",
                "Blake",
                "Bob",
                "Bobby",
                "Brad",
                "Brandon",
                "Brant",
                "Brent",
                "Brian",
                "Brown",
                "Bruce",
                "Caleb",
                "Cameron",
                "Carl",
                "Carlos",
                "Cary",
                "Caspar",
                "Cecil",
                "Charles",
                "Cheney",
                "Chris",
                "Christian",
                "Christopher",
                "Clark",
                "Cliff",
                "Cody",
                "Cole",
                "Colin",
                "Cosmo",
                "Daniel",
                "Denny",
                "Darwin",
                "David",
                "Dennis",
                "Derek",
                "Dick",
                "Donald",
                "Douglas",
                "Duke",
                "Dylan",
                "Eddie",
                "Edgar",
                "Edison",
                "Edmund",
                "Edward",
                "Edwin",
                "Elijah",
                "Elliott",
                "Elvis",
                "Eric",
                "Ethan",
                "Eugene",
                "Evan",
                "Enterprise",
                "Ford",
                "Francis",
                "Frank",
                "Franklin",
                "Fred",
                "Gabriel",
                "Gaby",
                "Garfield",
                "Gary",
                "Gavin",
                "Geoffrey",
                "George",
                "Gino",
                "Glen",
                "Glendon",
                "Hank",
                "Hardy",
                "Harrison",
                "Harry",
                "Hayden",
                "Henry",
                "Hilton",
                "Hugo",
                "Hunk",
                "Howard",
                "Henry",
                "Ian",
                "Ignativs",
                "Ivan",
                "Isaac",
                "Isaiah",
                "Jack",
                "Jackson",
                "Jacob",
                "James",
                "Jason",
                "Jay",
                "Jeffery",
                "Jerome",
                "Jerry",
                "Jesse",
                "Jim",
                "Jimmy",
                "Joe",
                "John",
                "Johnny",
                "Jonathan",
                "Jordan",
                "Jose",
                "Joshua",
                "Justin",
                "Keith",
                "Ken",
                "Kennedy",
                "Kenneth",
                "Kenny",
                "Kevin",
                "Kyle",
                "Lance",
                "Larry",
                "Laurent",
                "Lawrence",
                "Leander",
                "Lee",
                "Leo",
                "Leonard",
                "Leopold",
                "Leslie",
                "Loren",
                "Lori",
                "Lorin",
                "Louis",
                "Luke",
                "Marcus",
                "Marcy",
                "Mark",
                "Marks",
                "Mars",
                "Marshal",
                "Martin",
                "Marvin",
                "Mason",
                "Matthew",
                "Max",
                "Michael",
                "Mickey",
                "Mike",
                "Nathan",
                "Nathaniel",
                "Neil",
                "Nelson",
                "Nicholas",
                "Nick",
                "Noah",
                "Norman",
                "Oliver",
                "Oscar",
                "Owen",
                "Patrick",
                "Paul",
                "Peter",
                "Philip",
                "Phoebe",
                "Quentin",
                "Randall",
                "Randolph",
                "Randy",
                "Ray",
                "Raymond",
                "Reed",
                "Rex",
                "Richard",
                "Richie",
                "Riley",
                "Robert",
                "Robin",
                "Robinson",
                "Rock",
                "Roger",
                "Ronald",
                "Rowan",
                "Roy",
                "Ryan",
                "Sam",
                "Sammy",
                "Samuel",
                "Scott",
                "Sean",
                "Shawn",
                "Sidney",
                "Simon",
                "Solomon",
                "Spark",
                "Spencer",
                "Spike",
                "Stanley",
                "Steve",
                "Steven",
                "Stewart",
                "Stuart",
                "Terence",
                "Terry",
                "Ted",
                "Thomas",
                "Tim",
                "Timothy",
                "Todd",
                "Tommy",
                "Tom",
                "Thomas",
                "Tony",
                "Tyler",
                "Ultraman",
                "Ulysses",
                "Van",
                "Vern",
                "Vernon",
                "Victor",
                "Vincent",
                "Warner",
                "Warren",
                "Wayne",
                "Wesley",
                "William",
                "Willy",
                "Zack",
                "Zachary",
                "Abigail",
                "Abby",
                "Ada",
                "Adelaide",
                "Adeline",
                "Alexandra",
                "Ailsa",
                "Aimee",
                "Alexis",
                "Alice",
                "Alicia",
                "Alina",
                "Allison",
                "Alyssa",
                "Amanda",
                "Amy",
                "Amber",
                "Anastasia",
                "Andrea",
                "Angel",
                "Angela",
                "Angelia",
                "Angelina",
                "Ann",
                "Anna",
                "Anne",
                "Annie",
                "Anita",
                "Ariel",
                "April",
                "Ashley",
                "Audrey",
                "Aviva",
                "Barbara",
                "Barbie",
                "Beata",
                "Beatrice",
                "Becky",
                "Bella",
                "Bess",
                "Bette",
                "Betty",
                "Blanche",
                "Bonnie",
                "Brenda",
                "Brianna",
                "Britney",
                "Brittany",
                "Camille",
                "Candice",
                "Candy",
                "Carina",
                "Carmen",
                "Carol",
                "Caroline",
                "Carry",
                "Carrie",
                "Cassandra",
                "Cassie",
                "Catherine",
                "Cathy",
                "Chelsea",
                "Charlene",
                "Charlotte",
                "Cherry",
                "Cheryl",
                "Chloe",
                "Chris",
                "Christina",
                "Christine",
                "Christy",
                "Cindy",
                "Claire",
                "Claudia",
                "Clement",
                "Cloris",
                "Connie",
                "Constance",
                "Cora",
                "Corrine",
                "Crystal",
                "Daisy",
                "Daphne",
                "Darcy",
                "Dave",
                "Debbie",
                "Deborah",
                "Debra",
                "Demi",
                "Diana",
                "Dolores",
                "Donna",
                "Dora",
                "Doris",
                "Edith",
                "Editha",
                "Elaine",
                "Eleanor",
                "Elizabeth",
                "Ella",
                "Ellen",
                "Ellie",
                "Emerald",
                "Emily",
                "Emma",
                "Enid",
                "Elsa",
                "Erica",
                "Estelle",
                "Esther",
                "Eudora",
                "Eva",
                "Eve",
                "Evelyn",
                "Fannie",
                "Fay",
                "Fiona",
                "Flora",
                "Florence",
                "Frances",
                "Frederica",
                "Frieda",
                "Flta",
                "Gina",
                "Gillian",
                "Gladys",
                "Gloria",
                "Grace",
                "Grace",
                "Greta",
                "Gwendolyn",
                "Hannah",
                "Haley",
                "Hebe",
                "Helena",
                "Hellen",
                "Henna",
                "Heidi",
                "Hillary",
                "Ingrid",
                "Isabella",
                "Ishara",
                "Irene",
                "Iris",
                "Ivy",
                "Jacqueline",
                "Jade",
                "Jamie",
                "Jane",
                "Janet",
                "Jasmine",
                "Jean",
                "Jenna",
                "Jennifer",
                "Jenny",
                "Jessica",
                "Jessie",
                "Jill",
                "Joan",
                "Joanna",
                "Jocelyn",
                "Joliet",
                "Josephine",
                "Josie",
                "Joy",
                "Joyce",
                "Judith",
                "Judy",
                "Julia",
                "Juliana",
                "Julie",
                "June",
                "Karen",
                "Karida",
                "Katherine",
                "Kate",
                "Kathy",
                "Katie",
                "Katrina",
                "Kay",
                "Kayla",
                "Kelly",
                "Kelsey",
                "Kimberly",
                "Kitty",
                "Lareina",
                "Lassie",
                "Laura",
                "Lauren",
                "Lena",
                "Lydia",
                "Lillian",
                "Lily",
                "Linda",
                "lindsay",
                "Lisa",
                "Liz",
                "Lora",
                "Lorraine",
                "Louisa",
                "Louise",
                "Lucia",
                "Lucy",
                "Lucine",
                "Lulu",
                "Lydia",
                "Lynn",
                "Mabel",
                "Madeline",
                "Maggie",
                "Mamie",
                "Manda",
                "Mandy",
                "Margaret",
                "Mariah",
                "Marilyn",
                "Martha",
                "Mavis",
                "Mary",
                "Matilda",
                "Maureen",
                "Mavis",
                "Maxine",
                "May",
                "Mayme",
                "Megan",
                "Melinda",
                "Melissa",
                "Melody",
                "Mercedes",
                "Meredith",
                "Mia",
                "Michelle",
                "Milly",
                "Miranda",
                "Miriam",
                "Miya",
                "Molly",
                "Monica",
                "Morgan",
                "Nancy",
                "Natalie",
                "Natasha",
                "Nicole",
                "Nikita",
                "Nina",
                "Nora",
                "Norma",
                "Nydia",
                "Octavia",
                "Olina",
                "Olivia",
                "Ophelia",
                "Oprah",
                "Pamela",
                "Patricia",
                "Patty",
                "Paula",
                "Pauline",
                "Pearl",
                "Peggy",
                "Philomena",
                "Phoebe",
                "Phyllis",
                "Polly",
                "Priscilla",
                "Quentina",
                "Rachel",
                "Rebecca",
                "Regina",
                "Rita",
                "Rose",
                "Roxanne",
                "Ruth",
                "Sabrina",
                "Sally",
                "Sandra",
                "Samantha",
                "Sami",
                "Sandra",
                "Sandy",
                "Sarah",
                "Savannah",
                "Scarlett",
                "Selma",
                "Selina",
                "Serena",
                "Sharon",
                "Sheila",
                "Shelley",
                "Sherry",
                "Shirley",
                "Sierra",
                "Silvia",
                "Sonia",
                "Sophia",
                "Stacy",
                "Stella",
                "Stephanie",
                "Sue",
                "Sunny",
                "Susan",
                "Tamara",
                "Tammy",
                "Tanya",
                "Tasha",
                "Teresa",
                "Tess",
                "Tiffany",
                "Tina",
                "Tonya",
                "Tracy",
                "Ursula",
                "Vanessa",
                "Venus",
                "Vera",
                "Vicky",
                "Victoria",
                "Violet",
                "Virginia",
                "Vita",
                "Vivian"
        };

    static String[] nation={
            "中国","蒙古","朝鲜","韩国","日本","菲律宾","越南","老挝","柬埔寨","缅甸","泰国","马来西亚","文莱","新加坡","印度尼西亚",
            "东帝汶","尼泊尔","不丹","孟加拉国","印度","巴基斯坦","斯里兰卡","马尔代夫",
            "哈萨克斯坦","吉尔吉斯斯坦","塔吉克斯坦","乌兹别克斯坦","土库曼斯坦","伊拉克","约旦","黎巴嫩","以色列","巴勒斯坦","沙特阿拉伯",
            "爱沙尼亚","拉脱维亚","立陶宛","白俄罗斯","俄罗斯","波兰","捷克","斯洛伐克","匈牙利","德国","奥地利","瑞士","英国","爱尔兰",
            "荷兰","比利时","卢森堡","法国","马耳他","西班牙","葡萄牙","美国","澳大利亚","新西兰"
};
    static String[] firstNameInside = {
            "赵" , "钱" , "孙" , "李" , "周" , "吴" , "郑" , "王",
            "冯" , "陈" , "楮" , "卫" , "蒋" , "沈" , "韩" , "杨",
            "朱" , "秦" , "尤" , "许" , "何" , "吕" , "施" , "张",
            "孔" , "曹" , "严" , "华" , "金" , "魏" , "陶" , "姜",
            "戚" , "谢" , "邹" , "喻" , "柏" , "水" , "窦" , "章",
            "云" , "苏" , "潘" , "葛" , "奚" , "范" , "彭" , "郎",
            "鲁" , "韦" , "昌" , "马" , "苗" , "凤" , "花" , "方",
            "俞" , "任" , "袁" , "柳" , "酆" , "鲍" , "史" , "唐",
            "费" , "廉" , "岑" , "薛" , "雷" , "贺" , "倪" , "汤",
            "滕" , "殷" , "罗" , "毕" , "郝" , "邬" , "安" , "常",
            "乐" , "于" , "时" , "傅" , "皮" , "卞" , "齐" , "康",
            "伍" , "余" , "元" , "卜" , "顾" , "孟" , "平" , "黄",
            "和" , "穆" , "萧" , "尹" , "姚" , "邵" , "湛" , "汪",
            "祁" , "毛" , "禹" , "狄" , "米" , "贝" , "明" , "臧",
            "计" , "伏" , "成" , "戴" , "谈" , "宋" , "茅" , "庞",
            "熊" , "纪" , "舒" , "屈" , "项" , "祝" , "董" , "梁",
            "杜" , "阮" , "蓝" , "闽" , "席" , "季" , "麻" , "强",
            "贾" , "路" , "娄" , "危" , "江" , "童" , "颜" , "郭",
            "梅" , "盛" , "林" , "刁" , "锺" , "徐" , "丘" , "骆",
            "高" , "夏" , "蔡" , "田" , "樊" , "胡" , "凌" , "霍",
            "虞" , "万" , "支" , "柯" , "昝" , "管" , "卢" , "莫",
            "经" , "房" , "裘" , "缪" , "干" , "解" , "应" , "宗",
            "丁" , "宣" , "贲" , "邓" , "郁" , "单" , "杭" , "洪",
            "包" , "诸" , "左" , "石" , "崔" , "吉" , "钮" , "龚",
            "程" , "嵇" , "邢" , "滑" , "裴" , "陆" , "荣" , "翁",
            "荀" , "羊" , "於" , "惠" , "甄" , "麹" , "家" , "封",
            "芮" , "羿" , "储" , "靳" , "汲" , "邴" , "糜" , "松",
            "井" , "段" , "富" , "巫" , "乌" , "焦" , "巴" , "弓",
            "牧" , "隗" , "山" , "谷" , "车" , "侯" , "宓" , "蓬",
            "全" , "郗" , "班" , "仰" , "秋" , "仲" , "伊" , "宫",
            "宁" , "仇" , "栾" , "暴" , "甘" , "斜" , "厉" , "戎",
            "祖" , "武" , "符" , "刘" , "景" , "詹" , "束" , "龙",
            "叶" , "幸" , "司" , "韶" , "郜" , "黎" , "蓟" , "薄",
            "印" , "宿" , "白" , "怀" , "蒲" , "邰" , "从" , "鄂",
            "索" , "咸" , "籍" , "赖" , "卓" , "蔺" , "屠" , "蒙",
            "池" , "乔" , "阴" , "郁" , "胥" , "能" , "苍" , "双",
            "闻" , "莘" , "党" , "翟" , "谭" , "贡" , "劳" , "逄",
            "姬" , "申" , "扶" , "堵" , "冉" , "宰" , "郦" , "雍",
            "郤" , "璩" , "桑" , "桂" , "濮" , "牛" , "寿" , "通",
            "边" , "扈" , "燕" , "冀" , "郏" , "浦" , "尚" , "农",
            "温" , "别" , "庄" , "晏" , "柴" , "瞿" , "阎" , "充",
            "慕" , "连" , "茹" , "习" , "宦" , "艾" , "鱼" , "容",
            "向" , "古" , "易" , "慎" , "戈" , "廖" , "庾" , "终",
            "暨" , "居" , "衡" , "步" , "都" , "耿" , "满" , "弘",
            "匡" , "国" , "文" , "寇" , "广" , "禄" , "阙" , "东",
            "欧" , "殳" , "沃" , "利" , "蔚" , "越" , "夔" , "隆",
            "师" , "巩" , "厍" , "聂" , "晁" , "勾" , "敖" , "融",
            "冷" , "訾" , "辛" , "阚" , "那" , "简" , "饶" , "空",
            "曾" , "毋" , "沙" , "乜" , "养" , "鞠" , "须" , "丰",
            "巢" , "关" , "蒯" , "相" , "查" , "后" , "荆" , "红",
            "游" , "竺" , "权" , "逑" , "盖" , "益" , "桓" , "公",
            "万俟" , "司马" , "上官" , "欧阳",
            "夏侯" , "诸葛" , "闻人" , "东方",
            "赫连" , "皇甫" , "尉迟" , "公羊",
            "澹台" , "公冶" , "宗政" , "濮阳",
            "淳于" , "单于" , "太叔" , "申屠",
            "公孙" , "仲孙" , "轩辕" , "令狐",
            "锺离" , "宇文" , "长孙" , "慕容",
            "鲜于" , "闾丘" , "司徒" , "司空",
            "丌官" , "司寇" , "仉" , "督" , "子车",
            "颛孙" , "端木" , "巫马" , "公西",
            "漆雕" , "乐正" ,  "公良",
            "拓拔" , "夹谷" , "宰父" , "谷梁",
            "晋" , "楚" , "阎" , "法" , "汝" ,  "涂" , "钦",
            "段干" , "百里" , "东郭" , "南门",
            "呼延" , "归" , "海" , "羊舌" , "微生",
            "岳" , "帅" , "缑" , "亢" , "况" , "后" , "有" , "琴",
            "梁丘" , "左丘" , "东门" , "西门",
            "商" , "牟" , "佘" , "佴" , "伯" , "赏" , "南宫",
            "墨" ,  "年" , "爱" , "阳" , "佟",
            "第五" , "言" , "福"
    };


    private Random random=new Random();

    /**
     * 使用数组的方式存储姓氏
     * @return 数组中随机下标的字符串
     */
    private String insideFirstName() {
        int i = random.nextInt(firstNameInside.length);//[0,n)
        return firstNameInside[i];
    }

    /**
     * 去掉了相当多的繁体字
     * @return 随机生成一个汉字
     */
    private String insideSimpleLastName(){
        int hight,low;//二进制的高低位
        Random random= new Random();
        StringBuilder sBuilder = new StringBuilder();

        int lastLenght = 1+random.nextInt(2);

        for(int i=0;i<lastLenght;i++) {
            hight = 176+random.nextInt(39);
            low = 161+random.nextInt(93);
            byte[]han = new byte[2];
            han[0]= new Integer(hight).byteValue();
            han[1]= new Integer(low).byteValue();
            try {
                sBuilder.append(new String(han,"gbk"));
            } catch (UnsupportedEncodingException e) {
                e.printStackTrace();
            }
        }
        return sBuilder.toString();
    }

    private String getEnglishName() {
        int i = random.nextInt(namesEn.length);//[0,n)
        return namesEn[i];
    }
    /**
     * @return 全名
     */

    public Message getMessage() {
        Message message=new Message();
        int i = random.nextInt(nation.length);//[0,n)
        message.nation=nation[i];
        if(i<=5)message.name= insideFirstName()+insideSimpleLastName();
        else{
            message.name=getEnglishName();
        }
        return message;
    }

    public List<Message> getMessageList(int n) {
        List<Message> messages=new ArrayList<>();
        int i = random.nextInt(nation.length);//[0,n)
        for(int j=0;j<n;j++){
           if(i<=5) messages.add(new Message(insideFirstName()+insideSimpleLastName(),nation[i]));
           else{
               messages.add(new Message(getEnglishName(),nation[i]));
           }
        }
        return messages;
    }

}















